### ISSUE TITLE
curious how well this works?

### ISSUE THREAD

**Issue by jbenet** [alexpmorris/dipfs#1]
Curious how well this works? 

Also, we'll likely be doing a blog post on how to mount IPFS. is this stable enough to point people this way?

**Comment by alexpmorris** [comment]
Hi Juan - it was working very well last time I tried it, and also worked on newer Windows operating systems with dokany which has support all the way up to Windows 10.  The only real issue was about getting the actual file size, as discussed on this thread: https://github.com/ipfs/go-ipfs/issues/959

I believe this is from the variable header for the encryption/hashing metadata.

> > The file sizes are larger than the actual content. At first I thought the overhead was 11 bytes, but then other files/blocks had only 8. Perhaps there is some way I missed to figure out the exact size. It would have been also useful if a request such as this would return size

**Comment by jbenet** [comment]
Ok thanks!
